/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDeclareActionRouteImport } from './routes/api/public/declare/action'
import { Route as ApiPublicDeclareChipsRouteImport } from './routes/api/public/declare/chips'
import { Route as ApiPublicDeclareConfigRouteImport } from './routes/api/public/declare/config'
import { Route as ApiPublicDeclareCreateRouteImport } from './routes/api/public/declare/create'
import { Route as ApiPublicDeclareJoinRouteImport } from './routes/api/public/declare/join'
import { Route as ApiPublicDeclareLeaveRouteImport } from './routes/api/public/declare/leave'
import { Route as ApiPublicDeclareStateRouteImport } from './routes/api/public/declare/state'
import { Route as ApiPublicDeclareTickRouteImport } from './routes/api/public/declare/tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeclareActionRoute = ApiPublicDeclareActionRouteImport.update({
  id: '/api/public/declare/action',
  path: '/api/public/declare/action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeclareChipsRoute = ApiPublicDeclareChipsRouteImport.update({
  id: '/api/public/declare/chips',
  path: '/api/public/declare/chips',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeclareConfigRoute = ApiPublicDeclareConfigRouteImport.update({
  id: '/api/public/declare/config',
  path: '/api/public/declare/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeclareCreateRoute = ApiPublicDeclareCreateRouteImport.update({
  id: '/api/public/declare/create',
  path: '/api/public/declare/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeclareJoinRoute = ApiPublicDeclareJoinRouteImport.update({
  id: '/api/public/declare/join',
  path: '/api/public/declare/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeclareLeaveRoute = ApiPublicDeclareLeaveRouteImport.update({
  id: '/api/public/declare/leave',
  path: '/api/public/declare/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeclareStateRoute = ApiPublicDeclareStateRouteImport.update({
  id: '/api/public/declare/state',
  path: '/api/public/declare/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeclareTickRoute = ApiPublicDeclareTickRouteImport.update({
  id: '/api/public/declare/tick',
  path: '/api/public/declare/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/declare/action': typeof ApiPublicDeclareActionRoute
  '/api/public/declare/chips': typeof ApiPublicDeclareChipsRoute
  '/api/public/declare/config': typeof ApiPublicDeclareConfigRoute
  '/api/public/declare/create': typeof ApiPublicDeclareCreateRoute
  '/api/public/declare/join': typeof ApiPublicDeclareJoinRoute
  '/api/public/declare/leave': typeof ApiPublicDeclareLeaveRoute
  '/api/public/declare/state': typeof ApiPublicDeclareStateRoute
  '/api/public/declare/tick': typeof ApiPublicDeclareTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/declare/action': typeof ApiPublicDeclareActionRoute
  '/api/public/declare/chips': typeof ApiPublicDeclareChipsRoute
  '/api/public/declare/config': typeof ApiPublicDeclareConfigRoute
  '/api/public/declare/create': typeof ApiPublicDeclareCreateRoute
  '/api/public/declare/join': typeof ApiPublicDeclareJoinRoute
  '/api/public/declare/leave': typeof ApiPublicDeclareLeaveRoute
  '/api/public/declare/state': typeof ApiPublicDeclareStateRoute
  '/api/public/declare/tick': typeof ApiPublicDeclareTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/declare/action': typeof ApiPublicDeclareActionRoute
  '/api/public/declare/chips': typeof ApiPublicDeclareChipsRoute
  '/api/public/declare/config': typeof ApiPublicDeclareConfigRoute
  '/api/public/declare/create': typeof ApiPublicDeclareCreateRoute
  '/api/public/declare/join': typeof ApiPublicDeclareJoinRoute
  '/api/public/declare/leave': typeof ApiPublicDeclareLeaveRoute
  '/api/public/declare/state': typeof ApiPublicDeclareStateRoute
  '/api/public/declare/tick': typeof ApiPublicDeclareTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/declare/action'
    | '/api/public/declare/chips'
    | '/api/public/declare/config'
    | '/api/public/declare/create'
    | '/api/public/declare/join'
    | '/api/public/declare/leave'
    | '/api/public/declare/state'
    | '/api/public/declare/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/declare/action'
    | '/api/public/declare/chips'
    | '/api/public/declare/config'
    | '/api/public/declare/create'
    | '/api/public/declare/join'
    | '/api/public/declare/leave'
    | '/api/public/declare/state'
    | '/api/public/declare/tick'
  id:
    | '__root__'
    | '/'
    | '/api/public/declare/action'
    | '/api/public/declare/chips'
    | '/api/public/declare/config'
    | '/api/public/declare/create'
    | '/api/public/declare/join'
    | '/api/public/declare/leave'
    | '/api/public/declare/state'
    | '/api/public/declare/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicDeclareActionRoute: typeof ApiPublicDeclareActionRoute
  ApiPublicDeclareChipsRoute: typeof ApiPublicDeclareChipsRoute
  ApiPublicDeclareConfigRoute: typeof ApiPublicDeclareConfigRoute
  ApiPublicDeclareCreateRoute: typeof ApiPublicDeclareCreateRoute
  ApiPublicDeclareJoinRoute: typeof ApiPublicDeclareJoinRoute
  ApiPublicDeclareLeaveRoute: typeof ApiPublicDeclareLeaveRoute
  ApiPublicDeclareStateRoute: typeof ApiPublicDeclareStateRoute
  ApiPublicDeclareTickRoute: typeof ApiPublicDeclareTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/declare/action': {
      id: '/api/public/declare/action'
      path: '/api/public/declare/action'
      fullPath: '/api/public/declare/action'
      preLoaderRoute: typeof ApiPublicDeclareActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/declare/chips': {
      id: '/api/public/declare/chips'
      path: '/api/public/declare/chips'
      fullPath: '/api/public/declare/chips'
      preLoaderRoute: typeof ApiPublicDeclareChipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/declare/config': {
      id: '/api/public/declare/config'
      path: '/api/public/declare/config'
      fullPath: '/api/public/declare/config'
      preLoaderRoute: typeof ApiPublicDeclareConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/declare/create': {
      id: '/api/public/declare/create'
      path: '/api/public/declare/create'
      fullPath: '/api/public/declare/create'
      preLoaderRoute: typeof ApiPublicDeclareCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/declare/join': {
      id: '/api/public/declare/join'
      path: '/api/public/declare/join'
      fullPath: '/api/public/declare/join'
      preLoaderRoute: typeof ApiPublicDeclareJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/declare/leave': {
      id: '/api/public/declare/leave'
      path: '/api/public/declare/leave'
      fullPath: '/api/public/declare/leave'
      preLoaderRoute: typeof ApiPublicDeclareLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/declare/state': {
      id: '/api/public/declare/state'
      path: '/api/public/declare/state'
      fullPath: '/api/public/declare/state'
      preLoaderRoute: typeof ApiPublicDeclareStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/declare/tick': {
      id: '/api/public/declare/tick'
      path: '/api/public/declare/tick'
      fullPath: '/api/public/declare/tick'
      preLoaderRoute: typeof ApiPublicDeclareTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicDeclareActionRoute: ApiPublicDeclareActionRoute,
  ApiPublicDeclareChipsRoute: ApiPublicDeclareChipsRoute,
  ApiPublicDeclareConfigRoute: ApiPublicDeclareConfigRoute,
  ApiPublicDeclareCreateRoute: ApiPublicDeclareCreateRoute,
  ApiPublicDeclareJoinRoute: ApiPublicDeclareJoinRoute,
  ApiPublicDeclareLeaveRoute: ApiPublicDeclareLeaveRoute,
  ApiPublicDeclareStateRoute: ApiPublicDeclareStateRoute,
  ApiPublicDeclareTickRoute: ApiPublicDeclareTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
