// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhrzeakxthmtipwkrxzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ocnplYWt4dGhtdGlwd2tyeHpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTEwOTMwNzIsImV4cCI6MjEwNjY2OTA3Mn0.ZwxrG4fWusNIRrP1mz9Hdrj7QfXNVfc0FdJrLFzoj48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});